### PR TITLE
Code encapsulation

### PR DESCRIPTION
**Pull request by Ahamek**
I have significantly improved the main '**_Generator_**' class of the programme by separating the repetitive code from the _reqestPassword_ method. I separated the method responsible for communication with the user (_mainLoop_) and moved its execution to the '**_Main_**' class. I removed unnecessary variables and reduced the number of created objects (especially scanners). I also made some small improvements to the '**_Password_**' class. Lastly I modified the access specifiers so that in the '**_Generator_**' class only the _mainloop_ is public.

### CODE REVIEW

**Comment by KZarzour** [comment]
Hello, may I ask what made you interested in contributing to this project?

**Comment by Ahamek** [comment]
I really liked the idea of the project and thought it would be worth refreshing a bit as it may be useful to others

**Comment by KZarzour** [comment]
Did you change any functionality? 
Do all test cases work successfully?

**Comment by Ahamek** [comment]
yes the code is working everything has been checked. In terms of functionality, I have not added anything

**Comment by KZarzour** [comment]
So just restructuring? 
Thank you for your work, I gave it a quick glance and it looks good. I will review the changes later.

**Pull request merged**
